blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DiscussÃµes Gerais
    url: https://github.com/renantoniolo/futebadosparcas/discussions
    about: Para dÃºvidas gerais, ideias e feedback sobre o projeto
  - name: ğŸ“– DocumentaÃ§Ã£o
    url: https://github.com/renantoniolo/futebadosparcas/wiki
    about: Consulte a documentaÃ§Ã£o do projeto antes de abrir uma issue
